---
title: "Sales"
author: "Francis"
date: "August 16, 2018"
output: html_document
---

Dataset Description
Dataset: SalesData.dat

Source: Input from General Store Ledger Year 1921

Description: Each page includes purchases from one customer

Variables/columns
Date  24
Item  18          
Units 11
Quantity  num
Cost  int

Read in data 
```{r}
data <- read.table("C:/Users/rolsson/Desktop/GS 1921.txt", header = T)
```
Loading Libraries

```{r}
library(ggplot2)

```

Exploratory Data Analysis
```{r}
str(data)
sum(data$Cost)
IQR(data$Cost)
median(data$Cost)
tobacco.Cost <- subset(data$Cost, data$Item == "Tobacco")
sum(tobacco.Cost)
IQR(tobacco.Cost)
median(tobacco.Cost)
flour.Cost <- subset(data$Cost, data$Item == "Flour")
sum(flour.Cost)
IQR(flour.Cost)
median(flour.Cost)
tobacco.Price <- subset(data$Cost/data$Quantity, data$Item == "Tobacco")
sum(tobacco.Price)
IQR(tobacco.Price)
median(tobacco.Price)
flour.Price <- subset(data$Cost/data$Quantity, data$Item == "Flour")
sum(flour.Price)
IQR(flour.Price)
median(flour.Price)
```
Histograms


```{r}
hist(data$Cost)
hist(flour.Cost, right = TRUE)
hist(flour.Price, right = TRUE)
hist(tobacco.Cost, right = TRUE)
hist(tobacco.Price, right = TRUE)

```
Boxplots

```{r}
boxplot(data$Cost)
boxplot(flour.Cost)
boxplot(flour.Price)
boxplot(tobacco.Cost)
boxplot(tobacco.Price)


```